### ISSUE TITLE
Add Minecraft Wiki

### ISSUE THREAD

**Issue by CapoFantasma97** [alex4401/wikigg-redirect-extension#24]
**Info**
The scope could be extended to every official Wiki and not just wiki.gg ones.
Minecraft is migrating to a new, much better wiki website, but Fandom still takes the first search results page.

**Fandom Wiki:** https://minecraft.fandom.com/
**Official Wiki:** https://minecraft.wiki/

**Comment by alex4401** [comment]
I would claim that [Indie Wiki Buddy](https://github.com/KevinPayravi/indie-wiki-buddy) already takes good care of indie/nearly-indie wikis (which Minecraft qualifies as). I don't think there's a need to cross over into IWB's domain when both extensions can simply co-exist.

**Comment by macks2008** [comment]
Can both extensions not work together on this somehow so I don't have to install multiple extensions if I don't want to? Perhaps by either adding a user-defined list of additional wikis, or decoupling the list from the extension completely and making the "list of redirects to implement" a shared project?
For now I will probably get the other extension you mentioned (Especially since its namesake purpose fits my intention anyway. I love all things indie), but as these are both open source projects I would encourage collaboration.
